import esbuild from "esbuild";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Leave out library code the plugin never runs, so main.js stays small enough for Obsidian
 * Sync's 5 MB limit.
 */
const slimDependencies = {
	name: "slim-dependencies",
	setup(build) {
		// The lib uses only NodeFileSystem and NodePath, but the package index also brings in
		// the undici HTTP client, which needs node:sqlite. NodeFileSystem serves only the lib's
		// CLI runtime; the plugin provides a vault-based FileSystem, so it becomes an empty layer
		// and main.js doesn't contain Node's fs module.
		build.onResolve({ filter: /^@effect\/platform-node$/ }, (args) => ({
			path: args.path,
			namespace: "slim-platform-node",
		}));
		build.onLoad({ filter: /.*/, namespace: "slim-platform-node" }, () => ({
			contents: [
				'import * as Layer from "effect/Layer";',
				"export const NodeFileSystem = { layer: Layer.empty };",
				'export * as NodePath from "@effect/platform-node/NodePath";',
			].join("\n"),
			resolveDir: process.cwd(),
			loader: "js",
		}));
		// The lib renders math with MathJax's TeX font, so MathJax's default font is never used.
		build.onResolve({ filter: /^#default-font\/svg\/default\.js$/ }, (args) =>
			build.resolve("@mathjax/mathjax-tex-font/js/svg/default.js", {
				kind: args.kind,
				resolveDir: args.resolveDir,
			}),
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
	format: "cjs",
	platform: "browser",
	target: "chrome106",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	// Obsidian loads main.js from the plugin folder; main.js is gitignored and shipped only in releases.
	outfile: "main.js",
	plugins: [slimDependencies],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
